name: Count Lines 
on: [pull_request]

jobs:
  count-lines-of-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: chmod +x ./.github/workflows/countline.sh

      - run: ./.github/workflows/countline.sh 